name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: ["feature"]
assignees:
  - ViralEntity
  - Jubidition
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Please check this is a new issue before posting.        
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feature
    attributes:
      label: What Feature would you like to add?
      description: Please make sure to be descriptive as possible.
      placeholder: I'd like free candy with every update.
#      value: "An issue happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: "Please enter the exact version you downloaded."
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which variant are you using?
      multiple: true
      options:
        - GR6
        - GR9
  - type: textarea
    id: photod
    attributes:
      label: Relevant info.
      description: Please feel free to share any useful into and photos about this feature.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true